from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # REST API root view (generated by DRF router)
    url(r'^admin/', admin.site.urls),#ex:
    # url(r'^webapp/', include('webapp.urls')), #ex:
    url(r'^webapp2/', include('webappsql.urls')), #ex:
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)