from django.conf.urls import include, url
from django.contrib import admin
from rest_framework import routers
from webapp import views
from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='Django REST API')


# this is DRF router for REST API viewsets
router = routers.DefaultRouter()


# register REST API endpoints with DRF router
router.register(r'products', views.ProductViewSet , r"products")
router.register(r'users', views.UserViewSet , r"users")

urlpatterns = [
    # REST API root view (generated by DRF router)
    url(r'^api-authenticated/', include(router.urls, namespace='api')),#ex:
    url(r'^api/$', views.product_list),#ex:
    url(r'^api/max/(?P<pk>[0-9]+)$', views.product_list_by_max),#ex:
    url(r'^docs/', schema_view),#ex:
    url(r'^admin/', admin.site.urls),#ex:
]